### ISSUE TITLE
Question marks in song titles.

### ISSUE THREAD

**Issue by nemasu** [jaymoulin/google-music-manager-downloader#1]
Hello, I think the downloader crashes when a '?' is in a song title.
I'm using windows, downloaded from pip.

```
  File "c:\users\nemas\appdata\local\programs\python\python37\lib\site-packages\google_music_manager_downloader\download.py", line 41, in download
    with open(file_path, 'wb') as f:
OSError: [Errno 22] Invalid argument: b'.\\Album\\01 - A song?.mp3'
```

**Comment by jaymoulin** [comment]
Thank you for reporting this.

If you find this product useful, please consider donating to help me maintain/create great products (e.g. https://patreon.com/femtopixel.com).
